kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - cp -r /drone/src/ /project/
    - phpcs --standard=PSR1,PSR2 --ignore=/apps/my-symfony-app/vendor/ --ignore=/apps/my-symfony-app/app/config/ --extensions=php .

trigger:
  branch:
  - master
