kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - cp -r /drone/src/ /project/
    - phpcs --standard=PSR1,PSR2 --ignore=/vendor/ --ignore=/app/config/ .

trigger:
  branch:
  - master
