kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .

trigger:
  branch:
  - master
