kind: pipeline
name: default
#type: docker

#platform:
#  os: linux
#  arch: arm64

steps:
- name: nginx
  image: nginx:1.15.3-alpine
  commands:
    - echo "zebbi on the top"
#  volumes:
#  - name: nginx-config-dir
#    path: /etc/nginx/conf.d

- name: php
  image: php:7.3-fpm
  commands:
    - docker-php-ext-install pdo_mysql
    - pecl install apcu
    - apt-get update && \ apt-get install -y \ zlib1g-dev
    - docker-php-ext-install zip
    - docker-php-ext-enable apcu
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \ && php -r "if (hash_file('SHA384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \ && php composer-setup.php --filename=composer \ && php -r "unlink('composer-setup.php');" \ && mv composer /usr/local/bin/composer
    - WORKDIR /usr/src/app
    - COPY apps/my-symfony-app /usr/src/app
    - RUN PATH=$PATH:/usr/src/apps/vendor/bin:bin

  #volumes:
  #- name: project-dir
  #  path: /usr/src/app
  #environment:  

- name: test
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master
  depends_on:
  - nginx
  - php  

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

  depends_on:
  - test
  

trigger:
  branch:
  - master

#volumes:
#- name: project-dir
#  host:
#    path: /drone/src
#- name: nginx-config-dir
#  host:
#    path: /drone/src

#share workspace between pipeline
#workspace:
#  base: /
#  path: apps/my-symfony-app/ 