kind: pipeline
name: default
#type: docker

platform:
  os: linux
  arch: arm64

steps:
- name: install
  image: nginx:1.15.3-alpine
  dockerfile: docker/php/Dockerfile
  commands:
    - composer install 

- name: test
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master
  depends_on:
  - install  

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

  depends_on:
  - test
  

trigger:
  branch:
  - master