kind: pipeline
name: default

steps:
  coding style:
    image: grachev/php-cs-fixer
    commands:
      - >-
        php-cs-fixer fix
        --config=.php_cs.dist
        --verbose
        --dry-run
        --using-cache=no
        --path-mode=intersection
        `git diff --name-only --diff-filter=ACMRTUXB HEAD^`
