kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master

- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: drone
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

trigger:
  branch:
  - master
