kind: pipeline
name: default
#type: docker

#platform:
#  os: linux
#  arch: arm64

steps:
- name: nginx
  image: nginx:1.15.3-alpine
  commands:
    - echo "zebbi on the top"
#  volumes:
#  - name: nginx-config-dir
#    path: /etc/nginx/conf.d

- name: php
  image: php:7.3-fpm
  commands:
    - docker-php-ext-install pdo_mysql
    - pecl install apcu
    - RUN apt-get update && \ apt-get install -y \ zlib1g-dev
    
  #volumes:
  #- name: project-dir
  #  path: /usr/src/app
  #environment:  

- name: test
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master
  depends_on:
  - nginx
  - php  

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

  depends_on:
  - test
  

trigger:
  branch:
  - master

#volumes:
#- name: project-dir
#  host:
#    path: /drone/src
#- name: nginx-config-dir
#  host:
#    path: /drone/src

#share workspace between pipeline
#workspace:
#  base: /
#  path: apps/my-symfony-app/ 