kind: pipeline
name: default
#type: docker

#platform:
#  os: linux
#  arch: arm64

steps:
- name: nginx
  image: nginx:1.15.3-alpine
  dockerfile: docker/php/Dockerfile
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
    - composer install 

- name: php
  settings:
    - dockerfile: docker/php/Dockerfile
  volumes:
  - name: project-dir
    path: /usr/src/app
  #environment:  

- name: test
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master
  depends_on:
  - nginx
  - php  

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

  depends_on:
  - test
  

trigger:
  branch:
  - master

volumes:
- name: project-dir
  host:
    path: ./apps/my-symfony-app
- name: nginx-config-dir
  host:
    path: ./docker/nginx

#share workspace between pipeline
#workspace:
#  base: /
#  path: apps/my-symfony-app/ 