kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=/drone/src/apps/my-symfony-app/vendor/* --ignore=/drone/src/apps/my-symfony-app/config/* --extensions=php .

trigger:
  branch:
  - master
