pipeline:
  install:
    image: alexislefebvre/docker-images:7.2-alpine-composer
    volumes:
      - composer-cache:/root/.composer
    commands:
      - composer install --no-progress
    environment:
      - SYMFONY_ENV=test
  phpunit:
    image: alexislefebvre/docker-images:7.2-alpine-composer
    commands:
      - php vendor/bin/phpunit
    environment:
      - SYMFONY_ENV=test
