kind: pipeline
name: default
#type: kubernetes


steps:
- name: PSR2
  image: herloct/phpcs
  commands:
    - phpcs --standard=PSR1,PSR2 --ignore=apps/my-symfony-app/config/*,apps/my-symfony-app/public  --extensions=php .
  when:
    branch:
    - master

- name: notify
  image: plugins/slack
  with: # Set the secret as an input
      super_secret: ${{ secrets.SLACK_WEBHOOK }}
  settings:
    webhook: 
      from_secret: slack_webhook

trigger:
  branch:
  - master
