version:  '3.7'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - mysql  

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    networks:
      - mysql
      - php
    depends_on:
      - mysql  
    volumes:
      - './apps/my-symfony-app:/usr/src/app'
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 81:80
    networks:
      - php
    depends_on:
      - php


networks:
    mysql:
    php: